# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Sa', 'Sad'), ('An', 'Angry'), ('Co', 'Confused'), ('Ha', 'Happy'), ('De', 'Depressed'), ('Ax', 'anxious'), ('Wo', 'worried'), ('Fr', 'frightening')], max_length=2)),
                ('reason', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
