# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='state',
            field=models.CharField(choices=[('Sa', 'Sad'), ('An', 'Angry'), ('Co', 'Confused'), ('Ha', 'Happy'), ('Ro', 'Romantic'), ('De', 'Depressed'), ('Si', 'Sick'), ('Ax', 'anxious'), ('Wo', 'worried'), ('Fr', 'frightening')], max_length=2),
        ),
    ]
