# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0002_auto_20161213_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emotion',
            name='state',
            field=models.CharField(choices=[('Sa', 'Sad'), ('An', 'Angry'), ('Co', 'Confused'), ('Ha', 'Happy'), ('Ro', 'Romantic'), ('De', 'Depressed'), ('Si', 'Sick'), ('Ax', 'Anxious'), ('Wo', 'Worried'), ('Fr', 'Frightening')], max_length=2),
        ),
    ]
