# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0003_auto_20161216_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='reason',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
